### ISSUE TITLE
Setting up (Syntax error)

### ISSUE THREAD

**Issue by pintyoke** [redsudo/RedSea#31]
"2. Run `python redsea.py -h` to view the help file "

Result:
File "redsea.py", line 87
 print('<<< Getting {0} info... >>>'.format(MEDIA_TYPES[mt['type']]), end='\r') 
                                                                                                                ^
SyntaxError: invalid syntax

Environment:
(Debian 9.6, mutagen 1.31, pycryptodome 3.6.1, requests 2.9.1)

**Comment by Azalius** [comment]
Are you sure you are using python 3 to run it ? Try a `python --version` to be sure

**Comment by pintyoke** [comment]
Excuse me. I'm careless. I installed Python3 package, but it actually installed 2.

Thanks for the tip!
