### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by TheElectroclassics** [redsudo/RedSea#34]
Upon running RedSea for the first time, I get this error

`Traceback (most recent call last):
  File "redsea.py", line 7, in <module>
    from redsea.mediadownloader import MediaDownloader
  File "/Users/admin/Downloads/RedSea-master/redsea/mediadownloader.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by redsudo** [comment]
Which method of setup did you use? (you can find them here: https://github.com/redsudo/RedSea#setting-up-with-pip)

**Comment by redsudo** [comment]
Since this is a dependency issue that can be resolved by installing the `requests` package or following the installation instructions, I am closing this. Feel free to reopen if you have any issues.
