### ISSUE TITLE
Unknown file type to tag!

### ISSUE THREAD

**Issue by balleno75** [redsudo/RedSea#40]
Hello, when performing the next download in 320 quality,

https://tidal.com/album/103719628

The following error is generated,

# pipenv run python redsea.py -p 320 https://tidal.com/album/103719628

 /$$$$$$$                  /$$  /$$$$$$                     
| $$__  $$                | $$ /$$__  $$                    
| $$  \ $$  /$$$$$$   /$$$$$$$| $$  \__/  /$$$$$$   /$$$$$$ 
| $$$$$$$/ /$$__  $$ /$$__  $$|  $$$$$$  /$$__  $$ |____  $$
| $$__  $$| $$$$$$$$| $$  | $$ \____  $$| $$$$$$$$  /$$$$$$$
| $$  \ $$| $$_____/| $$  | $$ /$$  \ $$| $$_____/ /$$__  $$
| $$  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$/|  $$$$$$$|  $$$$$$$
|__/  |__/ \_______/ \_______/ \______/  \_______/ \_______/

                    (c) 2016 Joe Thatcher
               https://github.com/svbnet/RedSea

<<< Downloading album: 13 track(s) in total >>>
=== Downloading track ID 103719629 ===
	Track: 01
	Title: Demon
	Artist: Claudio Simonetti
	Album: Demons
	----
	Grabbing stream URL...
	Download progress: 100%
	Downloading album art...
	Download progress: 100%
	Tagging media file...
	Unknown file type to tag!
=== 1/13 complete (8% done) ===

At the end of the download, the files have no extension and do not have a data label.

-rw-r--r-- 1 root root 13755971 may 31 18:27 '01 - Demon.'
-rw-r--r-- 1 root root   187624 may 31 18:27  Cover.jpg
-rw-r--r-- 1 root root  2801085 may 31 18:27 '02 - Cruel Demon.'
-rw-r--r-- 1 root root  7854096 may 31 18:27 '03 - Killing.'
-rw-r--r-- 1 root root  3908320 may 31 18:27 '04 - Threat.'
-rw-r--r-- 1 root root  5054733 may 31 18:27 '05 - The Evil One.'
-rw-r--r-- 1 root root 10037809 may 31 18:27 '06 - Out of Time.'
-rw-r--r-- 1 root root  4129405 may 31 18:27 '07 - Demon (Reprise).'
-rw-r--r-- 1 root root 10608697 may 31 18:27 '08 - Demon'\''s Lounge (Previously Unreleased).'
-rw-r--r-- 1 root root 12352065 may 31 18:27 '09 - Demon (Demo Version 1985).'
-rw-r--r-- 1 root root 12327885 may 31 18:27 '10 - Killing (Demo Version 1985).'
-rw-r--r-- 1 root root 10298992 may 31 18:27 '11 - Demon (Demo played on Piano  1985).'
-rw-r--r-- 1 root root 11170230 may 31 18:27 '12 - Demon (Simonetti Horror Project Version 1990).'
-rw-r--r-- 1 root root 13023732 may 31 18:27 '13 - Demon (Daemonia Live in Los Angeles 2002).'

Please, can you check it? Thank you. A greeting.

**Comment by redsudo** [comment]
Alright pull the develop branch and test that. I found the issue and made a temporary fix. Going to make a better fix in the next proper release.

**Comment by balleno75** [comment]
Thank you. We are waiting impatiently for the new version. A greeting.

**Comment by redsudo** [comment]
Fixed in release 2.1.1
