### ISSUE TITLE
I can't create account

### ISSUE THREAD

**Issue by alexandrox** [redsudo/RedSea#58]
I'm trying login in RedSea but i have a issue I put my username, in password the cursor don't move but i put my pass and enter, then show What would you like to call this new session? I name any buth then it show newly what is your username.

**Comment by kkazakov** [comment]
I have the same problem and no solution yet :(

**Comment by kkazakov** [comment]
Okay, I found a solution. Check this issue raised - https://github.com/redsudo/RedSea/issues/57 and replace all the places where you see the token. Then try again to create a session and it finally works. I'm currently downloading.

**Comment by alexandrox** [comment]
Tkz, I checked it and work fine
