### ISSUE TITLE
My still not downloading

### ISSUE THREAD

**Issue by marasek12345** [redsudo/RedSea#59]
I replaced the token string with a new value wherever it appeared and create new session, but still not downloading files.

I have:
	4005: Asset is not ready for playback (HTTP 401)
	Stream could not be acquired

**Comment by firebfm** [comment]
Maybe it's still using the old one. Delete all sessions and try again.

**Comment by marasek12345** [comment]
I removed file "/config/sessions.pk" manualy and create new one by command:  "python3 redsea.py auth add".
Still have that same error:

4005: Asset is not ready for playback (HTTP 401)
Stream could not be acquired

Before I changed the file "tidal_api.py" I could not create a new session.
Session creation now works, but download no longer.

**Comment by firebfm** [comment]
python redsea.py auth reauth

**Comment by marasek12345** [comment]
still not work

**Comment by firebfm** [comment]
redsea.py auth remove. Don't use "python3 redsea.py auth add". Input a download link. It will then prompt for username and password.

**Comment by marasek12345** [comment]
I have Mac Os.
I use "python3 redsea.py auth remove" to remove default session.
Next run "python3 redsea.py https://xxxxxxxxxxxxxxx" and input username and password.
Session create ok with new token.
 Still not download

**Comment by marasek12345** [comment]
if i use python redsea.py https://xxxxxxxxxxxxxxx i have error
  File "./redsea.py", line 87
    print('<<< Getting {0} info... >>>'.format(MEDIA_TYPES[mt['type']]), end='\r')

**Comment by marasek12345** [comment]
I have always used python3 and it worked.
Not works since the token change.

**Comment by firebfm** [comment]
Go try on a windows computer or your tidal account expired. I am out of ideas.

**Comment by firebfm** [comment]
This is my tidal_api.py. http://www.mediafire.com/file/v59za46pan5bmvp/tidal_api.zip/file Use mine. Maybe you made a typo.

**Comment by marasek12345** [comment]
With new token is working. Close topic. thx
